drop table if exists dish;
drop table if exists restaurant;
drop table if exists user_roles;
drop table if exists users;
drop table if exists vote;

create table users
(
    id          integer generated by default as identity,
    name        varchar(100)                not null,
    email       varchar(100)                not null,
    enabled     bool        default true    not null,
    password    varchar(100)                not null,
    registered  timestamp   default now()   not null,
    primary key (id),
    constraint users_unique_email_idx unique (email)
);

create table user_roles
(
    user_id     integer         not null,
    role        varchar(255),
    constraint user_roles_idx unique (user_id, role)
);

create table restaurant
(
    id      integer generated by default as identity,
    name    varchar(100)                    not null,
    primary key (id),
    constraint restaurant_unique_name_idx unique (name)
);

create table dish
(
    id              integer  generated by default as identity,
    name            varchar(100)                    not null,
    date            date            default now()   not null,
    price           integer                         not null,
    restaurant_id   integer                         not null,
    primary key (id),
    constraint dish_unique_name_restaurant_date_idx unique (name, restaurant_id, date),
    foreign key (restaurant_id) references restaurant (id) on delete cascade
);

create table vote
(
    id              integer generated by default as identity,
    date            date    default now()   not null,
    restaurant_id   integer                 not null,
    user_id         integer                 not null,
    primary key (id),
    constraint vote_unique_user_date_idx unique (user_id, date),
    foreign key (user_id) references users (id) on delete cascade,
    foreign key (restaurant_id) references restaurant (id) on delete cascade
);